### login

POST http://localhost:4323/auth/login
Content-Type: application/json

{
  "email": "carlo@gmail.com",
  "password": "123"
}

### Register

POST http://localhost:4323/auth/register
Content-Type: application/json

{
  "name": "Pacheco mendez",
  "email": "pachecox@gmail.com",
  "password": "pachecox123!"
}


### register an medicament
POST http://localhost:4323/farmacia/adding
Content-Type: application/json

{
  "name": "XELOX",
  "userId": 3
}

### get all registers 
POST http://localhost:4323/farmacia/registers
Content-Type: application/json

{
  "userId": 3
}



### removing registr by id 
DELETE  http://localhost:4323/farmacia/removing
Content-Type: application/json

{
  "id": 3
}

